version: "3.8"
services:
  mongo_app:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD: 
  express-app:
    build: ./backend
    container_name: express-app
    ports:
      - 3000:3000
    depends_on:
      - mongo_app
    environment:
      - PORT=3000
      - JWT_SECRET=
      - MONGO_URI=
  vue-app:
    build: ./frontend
    container_name: vue-app
    ports:
      - 8000:8000
    depends_on:
      - mongo_app
      - express-app