version: "3.8"
services:
  mongo_db:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
  express-app:
    build: ./backend
    container_name: express-app
    ports:
      - 3000:3000
    depends_on:
      - mongo_db
    environment:
      - name=value
      - PORT=3000
      - DOMAIN=localhost
      - JWT_SECRET=los secretos para jwt deben de ser largos y seguros
  vue-app:
    build: ./frontend
    container_name: vue-app
    ports:
      - 8000:8000
    depends_on:
      - mongo_db
      - express-app